### ISSUE TITLE
wrong security code calculation

### ISSUE THREAD

**Issue by borisko1980** [nticaric/fiskalizacija#13]
The code for generating security code ( zastitni kod ) is wrong!
in class Bill method securityCode should be as follows: ( assuming $pkey contains private key string in PEM format ) ( no guarantees I got it correct, though - if not, maybe someone can correct it )

```php
public function securityCode( $pkey, $oib, $dt, $bor, $opp, $onu, $uir )
  {
    $ZastKodUnsigned = '';

    $ZastKodUnsigned .= $oib;
    $ZastKodUnsigned .= $dt;
    $ZastKodUnsigned .= $bor;
    $ZastKodUnsigned .= $opp;
    $ZastKodUnsigned .= $onu;
    $ZastKodUnsigned .= $uir;

    $ZastKodSignature = null;

    if ( !openssl_sign($ZastKodUnsigned, $ZastKodSignature, $pkey, OPENSSL_ALGO_SHA1) )
      throw new \Exception( 'Error creating security code' );

    $ZastKod = md5($ZastKodSignature);
    
    return $this->securityCode = $ZastKod;
}
```

**Comment by nticaric** [comment]
Feel free to create a pull request

**Comment by borisko1980** [comment]
Would love to, however I don't use github often and never created a pull request before - kinda a huge overhead for me to do at the moment.

In any case - I was going through the code and stumbled on the function to create the security code and it got me thinking that it would be a really bad design decision to actually use private key directly in calculating md5 - given that it is known to be really weak. Made me wonder if the guys at fina really intended it that way - so despite my lack of understanding of Croatian language I did manage to find in the documentation the pseudo algorithm ( apparently appendix 12 ) and it reads:
`MD5 hash (Elektronički potpis privatnim ključem (OIB+datum i vrijeme izdavanja+brojčana oznaka
računa+oznaka poslovnog prostora+oznaka naplatnog uređaja+ukupni iznos računa))`

To my understanding ( and also according to implementation examples below in the mentioned appendix ) it says that you are first to electronically sign ( meaning to compute SHA1 signature ) of concatenated items from the receipt, and from that you are to calculate md5 sum. 

In your code you are concatenating private key with the receipt items and from there you take md5 - I am guessing that if it were done this way, anyone could collect enough receipts from single cash desk and could actually find out the private key - just my wild assumption, not that anyone would actually want to do that in real life....

I don't know if fina is keeping private keys, e.g. if they actually have any means of finding out that the security code on a receipt is wrong, but if they didn't it, would lack any point in putting it on a receipt in the first place. For that matter I don't know what would the eventual fine be if they ever find out... ( If it is anything like in my country, they would surely love to fine you all they could )

Cheers.

**Comment by nticaric** [comment]
I am a little bit late with the answer :) but thanks for pointing that out. I'm happy to let you know that the issue has now been resolved and the calculation should now be correct
