### ISSUE TITLE
Poruka nije u skladu s XML shemom :  cvc-simple-type 1: element X509SerialNumber is not int

### ISSUE THREAD

**Issue by nmiodrag** [nticaric/fiskalizacija#14]
Javlja se greška da X509SerialNumber nije integer.
Rješenje:
Fiskalizacija.php linija 122 umjesto
		$X509SerialNumberNode = new DOMElement('X509SerialNumber',$X509IssuerSerial);
Treba biti:
		$X509SerialNumberNode = new DOMElement('X509SerialNumber',sprintf('%u',hexdec($X509IssuerSerial)));

**Comment by robier** [comment]
Dobio sam istu grešku, ali predloženo riješenje nije dobro jer vraca vrijednost 0, pošto se koristi krivi specifier u `sprintf` funkciji. Specifier `u` služi samo za int vrijednosti, a  funkcija `hexdec` vraca float. Iz tog razloga trebao bi se koristiti `F` specifier, pošto taj specifier hendla float type (i nije locale aware, za razliku od `f` specifiera).

Primjer podatka koji se nalazi u `$X509IssuerSerial` variabli `0x31EB5E6FE1AE2649000000005F345FA7`.

```php
echo sprintf('%.0F', hexdec('0x31EB5E6FE1AE2649000000005F345FA7')); // 66354276965890004357694471502095712256
```
